### ISSUE TITLE
CPU support?

### ISSUE THREAD

**Issue by ChameleonScales** [tom-doerr/TecoGAN#7]
In the readme, under "Install the NVIDIA Container Toolkit" it says:

> This step [...] is only necessary if you want GPU support.

So if I understand correctly, we can chose to use the CPU instead? If so, I didn't find how to do it.

I tried removing `--gpus all` from the `docker run` command but then when launching `runGan.py 1` I got :
```
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.
```

If using the CPU on the run case 1 is possible, I would like to do it for the following reasons:
1. the Nvidia Toolkit is not yet supported under the latest stable Ubuntu (20.10)
2. I have another computer with an AMD GPU which I would also like to run TecoGAN on

**Comment by tom-doerr** [comment]
The issue might be that the docker base image is build using a gpu base image.
In `docker/Dockerfile` you could change `from tensorflow/tensorflow:1.8.0-gpu-py3` to `from tensorflow/tensorflow:1.8.0-py3`, execute the docker build step and `runGan.py 1` should work on the CPU.

**Comment by ChameleonScales** [comment]
Thanks, it works great!
